//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotopecApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int IdPet { get; set; }
        public string Name { get; set; }
        public int Height { get; set; }
        public int Weight { get; set; }
        public string Breed { get; set; }
        public string Type { get; set; }
        public string Despription { get; set; }
        public byte[] ImagePet { get; set; }
    }
}
